// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: additional_documents.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const CountAdditionalDocumentsByEnvelope = `-- name: CountAdditionalDocumentsByEnvelope :one
SELECT COUNT(*) FROM additional_documents
WHERE envelope_id = $1
`

func (q *Queries) CountAdditionalDocumentsByEnvelope(ctx context.Context, envelopeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountAdditionalDocumentsByEnvelope, envelopeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateAdditionalDocument = `-- name: CreateAdditionalDocument :one
INSERT INTO additional_documents (
    id,
    created_at,
    envelope_id,
    document_checksum,
    document_content,
    media_type,
    is_ebl_visualisation
) VALUES (
    gen_random_uuid(),
    now(),
    $1, $2, $3, $4, $5
) RETURNING id, created_at, envelope_id, document_checksum, document_content, media_type, is_ebl_visualisation
`

type CreateAdditionalDocumentParams struct {
	EnvelopeID         uuid.UUID `json:"envelope_id"`
	DocumentChecksum   string    `json:"document_checksum"`
	DocumentContent    []byte    `json:"document_content"`
	MediaType          string    `json:"media_type"`
	IsEblVisualisation bool      `json:"is_ebl_visualisation"`
}

func (q *Queries) CreateAdditionalDocument(ctx context.Context, arg CreateAdditionalDocumentParams) (AdditionalDocument, error) {
	row := q.db.QueryRow(ctx, CreateAdditionalDocument,
		arg.EnvelopeID,
		arg.DocumentChecksum,
		arg.DocumentContent,
		arg.MediaType,
		arg.IsEblVisualisation,
	)
	var i AdditionalDocument
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.EnvelopeID,
		&i.DocumentChecksum,
		&i.DocumentContent,
		&i.MediaType,
		&i.IsEblVisualisation,
	)
	return i, err
}

const GetAdditionalDocument = `-- name: GetAdditionalDocument :one
SELECT id, created_at, envelope_id, document_checksum, document_content, media_type, is_ebl_visualisation FROM additional_documents
WHERE envelope_id = $1 AND document_checksum = $2
`

type GetAdditionalDocumentParams struct {
	EnvelopeID       uuid.UUID `json:"envelope_id"`
	DocumentChecksum string    `json:"document_checksum"`
}

func (q *Queries) GetAdditionalDocument(ctx context.Context, arg GetAdditionalDocumentParams) (AdditionalDocument, error) {
	row := q.db.QueryRow(ctx, GetAdditionalDocument, arg.EnvelopeID, arg.DocumentChecksum)
	var i AdditionalDocument
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.EnvelopeID,
		&i.DocumentChecksum,
		&i.DocumentContent,
		&i.MediaType,
		&i.IsEblVisualisation,
	)
	return i, err
}

const GetAdditionalDocumentChecksums = `-- name: GetAdditionalDocumentChecksums :many
SELECT document_checksum FROM additional_documents
WHERE envelope_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetAdditionalDocumentChecksums(ctx context.Context, envelopeID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, GetAdditionalDocumentChecksums, envelopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var document_checksum string
		if err := rows.Scan(&document_checksum); err != nil {
			return nil, err
		}
		items = append(items, document_checksum)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAdditionalDocumentsByEnvelope = `-- name: ListAdditionalDocumentsByEnvelope :many
SELECT id, created_at, envelope_id, document_checksum, document_content, media_type, is_ebl_visualisation FROM additional_documents
WHERE envelope_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAdditionalDocumentsByEnvelope(ctx context.Context, envelopeID uuid.UUID) ([]AdditionalDocument, error) {
	rows, err := q.db.Query(ctx, ListAdditionalDocumentsByEnvelope, envelopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdditionalDocument
	for rows.Next() {
		var i AdditionalDocument
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.EnvelopeID,
			&i.DocumentChecksum,
			&i.DocumentContent,
			&i.MediaType,
			&i.IsEblVisualisation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
