// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: additional_documents.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const CreateExpectedAdditionalDocument = `-- name: CreateExpectedAdditionalDocument :one
INSERT INTO additional_documents (
    id,
    created_at,
    envelope_id,
    document_checksum,
    document_name,
    expected_size,
    media_type,
    is_ebl_visualisation,
    document_content,
    received_at
) VALUES (
    gen_random_uuid(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    NULL, -- document_content (not received yet)
    NULL  -- received_at (not received yet)
) RETURNING id, created_at, envelope_id, document_checksum, document_name, expected_size, media_type, is_ebl_visualisation, document_content, received_at
`

type CreateExpectedAdditionalDocumentParams struct {
	EnvelopeID         uuid.UUID `json:"envelope_id"`
	DocumentChecksum   string    `json:"document_checksum"`
	DocumentName       string    `json:"document_name"`
	ExpectedSize       int64     `json:"expected_size"`
	MediaType          string    `json:"media_type"`
	IsEblVisualisation bool      `json:"is_ebl_visualisation"`
}

// Create a placeholder record for an expected additional document
func (q *Queries) CreateExpectedAdditionalDocument(ctx context.Context, arg CreateExpectedAdditionalDocumentParams) (AdditionalDocument, error) {
	row := q.db.QueryRow(ctx, CreateExpectedAdditionalDocument,
		arg.EnvelopeID,
		arg.DocumentChecksum,
		arg.DocumentName,
		arg.ExpectedSize,
		arg.MediaType,
		arg.IsEblVisualisation,
	)
	var i AdditionalDocument
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.EnvelopeID,
		&i.DocumentChecksum,
		&i.DocumentName,
		&i.ExpectedSize,
		&i.MediaType,
		&i.IsEblVisualisation,
		&i.DocumentContent,
		&i.ReceivedAt,
	)
	return i, err
}

const GetAdditionalDocument = `-- name: GetAdditionalDocument :one
SELECT id, created_at, envelope_id, document_checksum, document_name, expected_size, media_type, is_ebl_visualisation, document_content, received_at FROM additional_documents
WHERE envelope_id = $1
  AND document_checksum = $2
`

type GetAdditionalDocumentParams struct {
	EnvelopeID       uuid.UUID `json:"envelope_id"`
	DocumentChecksum string    `json:"document_checksum"`
}

func (q *Queries) GetAdditionalDocument(ctx context.Context, arg GetAdditionalDocumentParams) (AdditionalDocument, error) {
	row := q.db.QueryRow(ctx, GetAdditionalDocument, arg.EnvelopeID, arg.DocumentChecksum)
	var i AdditionalDocument
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.EnvelopeID,
		&i.DocumentChecksum,
		&i.DocumentName,
		&i.ExpectedSize,
		&i.MediaType,
		&i.IsEblVisualisation,
		&i.DocumentContent,
		&i.ReceivedAt,
	)
	return i, err
}

const GetMissingAdditionalDocumentChecksums = `-- name: GetMissingAdditionalDocumentChecksums :many
SELECT document_checksum FROM additional_documents
WHERE envelope_id = $1
  AND document_content IS NULL
ORDER BY document_checksum
`

// Get checksums of additional documents that haven't been received yet
func (q *Queries) GetMissingAdditionalDocumentChecksums(ctx context.Context, envelopeID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, GetMissingAdditionalDocumentChecksums, envelopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var document_checksum string
		if err := rows.Scan(&document_checksum); err != nil {
			return nil, err
		}
		items = append(items, document_checksum)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetReceivedAdditionalDocumentChecksums = `-- name: GetReceivedAdditionalDocumentChecksums :many
SELECT document_checksum FROM additional_documents
WHERE envelope_id = $1
  AND document_content IS NOT NULL
ORDER BY document_checksum
`

// Get checksums of additional documents that have been received
func (q *Queries) GetReceivedAdditionalDocumentChecksums(ctx context.Context, envelopeID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, GetReceivedAdditionalDocumentChecksums, envelopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var document_checksum string
		if err := rows.Scan(&document_checksum); err != nil {
			return nil, err
		}
		items = append(items, document_checksum)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateAdditionalDocumentContent = `-- name: UpdateAdditionalDocumentContent :exec
UPDATE additional_documents
SET 
    document_content = $3,
    received_at = NOW()
WHERE envelope_id = $1
  AND document_checksum = $2
`

type UpdateAdditionalDocumentContentParams struct {
	EnvelopeID       uuid.UUID `json:"envelope_id"`
	DocumentChecksum string    `json:"document_checksum"`
	DocumentContent  []byte    `json:"document_content"`
}

// Update additional document with received content
func (q *Queries) UpdateAdditionalDocumentContent(ctx context.Context, arg UpdateAdditionalDocumentContentParams) error {
	_, err := q.db.Exec(ctx, UpdateAdditionalDocumentContent, arg.EnvelopeID, arg.DocumentChecksum, arg.DocumentContent)
	return err
}
