// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdditionalDocument struct {
	ID                 uuid.UUID          `json:"id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	EnvelopeID         uuid.UUID          `json:"envelope_id"`
	DocumentChecksum   string             `json:"document_checksum"`
	DocumentName       string             `json:"document_name"`
	ExpectedSize       int64              `json:"expected_size"`
	MediaType          string             `json:"media_type"`
	IsEblVisualisation bool               `json:"is_ebl_visualisation"`
	DocumentContent    []byte             `json:"document_content"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
}

type Envelope struct {
	ID                                                 uuid.UUID          `json:"id"`
	CreatedAt                                          pgtype.Timestamptz `json:"created_at"`
	AcceptedAt                                         pgtype.Timestamptz `json:"accepted_at"`
	TransportDocumentChecksum                          string             `json:"transport_document_checksum"`
	LastTransferChainEntrySignedContentPayloadChecksum string             `json:"last_transfer_chain_entry_signed_content_payload_checksum"`
	LastTransferChainEntrySignedContentChecksum        string             `json:"last_transfer_chain_entry_signed_content_checksum"`
	ActionCode                                         string             `json:"action_code"`
	SentByPlatformCode                                 string             `json:"sent_by_platform_code"`
	ReceivedByPlatformCode                             string             `json:"received_by_platform_code"`
	EnvelopeManifestSignedContent                      string             `json:"envelope_manifest_signed_content"`
	LastTransferChainEntrySignedContent                string             `json:"last_transfer_chain_entry_signed_content"`
	TrustLevel                                         int32              `json:"trust_level"`
}

type Party struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	PartyName string             `json:"party_name"`
	Active    bool               `json:"active"`
}

type PartyIdentifyingCode struct {
	ID               uuid.UUID          `json:"id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	PartyID          uuid.UUID          `json:"party_id"`
	CodeListProvider string             `json:"code_list_provider"`
	PartyCode        string             `json:"party_code"`
	CodeListName     *string            `json:"code_list_name"`
}

type TransferChainEntry struct {
	SignedContentPayloadChecksum  string             `json:"signed_content_payload_checksum"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
	TransportDocumentChecksum     string             `json:"transport_document_checksum"`
	EnvelopeID                    uuid.UUID          `json:"envelope_id"`
	SignedContent                 string             `json:"signed_content"`
	SignedContentChecksum         string             `json:"signed_content_checksum"`
	PreviousSignedContentChecksum *string            `json:"previous_signed_content_checksum"`
	Sequence                      int32              `json:"sequence"`
}

type TransportDocument struct {
	Checksum  string             `json:"checksum"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Content   json.RawMessage    `json:"content"`
}

type TransportDocumentPossessor struct {
	EnvelopeID                uuid.UUID          `json:"envelope_id"`
	TransportDocumentChecksum string             `json:"transport_document_checksum"`
	ActionCode                string             `json:"action_code"`
	PossessorPlatformCode     string             `json:"possessor_platform_code"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	AcceptedAt                pgtype.Timestamptz `json:"accepted_at"`
}

type TransportDocumentState struct {
	EnvelopeID                uuid.UUID          `json:"envelope_id"`
	TransportDocumentChecksum string             `json:"transport_document_checksum"`
	ActionCode                string             `json:"action_code"`
	SentByPlatformCode        string             `json:"sent_by_platform_code"`
	ReceivedByPlatformCode    string             `json:"received_by_platform_code"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	Accepted                  interface{}        `json:"accepted"`
	AcceptedAt                pgtype.Timestamptz `json:"accepted_at"`
}
