// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parties.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const CreateParty = `-- name: CreateParty :one
INSERT INTO parties (id, created_at, updated_at, party_name, active)
VALUES (gen_random_uuid(), NOW(), NOW(), $1, $2)
RETURNING id, created_at, updated_at, party_name, active
`

type CreatePartyParams struct {
	PartyName string `json:"party_name"`
	Active    bool   `json:"active"`
}

func (q *Queries) CreateParty(ctx context.Context, arg CreatePartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, CreateParty, arg.PartyName, arg.Active)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PartyName,
		&i.Active,
	)
	return i, err
}

const CreatePartyIdentifyingCode = `-- name: CreatePartyIdentifyingCode :one
INSERT INTO party_identifying_codes (id, created_at,updated_at, party_id, code_list_provider, party_code, code_list_name)
VALUES (gen_random_uuid(), NOW(), NOW(), $1, $2, $3, $4)
RETURNING id, created_at, updated_at, party_id, code_list_provider, party_code, code_list_name
`

type CreatePartyIdentifyingCodeParams struct {
	PartyID          uuid.UUID `json:"party_id"`
	CodeListProvider string    `json:"code_list_provider"`
	PartyCode        string    `json:"party_code"`
	CodeListName     *string   `json:"code_list_name"`
}

func (q *Queries) CreatePartyIdentifyingCode(ctx context.Context, arg CreatePartyIdentifyingCodeParams) (PartyIdentifyingCode, error) {
	row := q.db.QueryRow(ctx, CreatePartyIdentifyingCode,
		arg.PartyID,
		arg.CodeListProvider,
		arg.PartyCode,
		arg.CodeListName,
	)
	var i PartyIdentifyingCode
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PartyID,
		&i.CodeListProvider,
		&i.PartyCode,
		&i.CodeListName,
	)
	return i, err
}

const GetPartyByID = `-- name: GetPartyByID :one
SELECT id, created_at, updated_at, party_name, active FROM parties
WHERE id = $1
`

func (q *Queries) GetPartyByID(ctx context.Context, id uuid.UUID) (Party, error) {
	row := q.db.QueryRow(ctx, GetPartyByID, id)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PartyName,
		&i.Active,
	)
	return i, err
}

const GetPartyByPartyCode = `-- name: GetPartyByPartyCode :one
SELECT p.id, p.created_at, p.updated_at, p.party_name, p.active
FROM parties p
INNER JOIN party_identifying_codes pic ON p.id = pic.party_id
WHERE pic.code_list_provider = $1
  AND pic.party_code = $2
  AND ($3::text IS NULL OR pic.code_list_name = $3::text)
  AND p.active = TRUE
LIMIT 1
`

type GetPartyByPartyCodeParams struct {
	CodeListProvider string  `json:"code_list_provider"`
	PartyCode        string  `json:"party_code"`
	CodeListName     *string `json:"code_list_name"`
}

// Lookup a party by their identifying code (for receiver validation endpoint)
// Only returns active parties
// code_list_name is optional - if NULL, it matches any code_list_name
func (q *Queries) GetPartyByPartyCode(ctx context.Context, arg GetPartyByPartyCodeParams) (Party, error) {
	row := q.db.QueryRow(ctx, GetPartyByPartyCode, arg.CodeListProvider, arg.PartyCode, arg.CodeListName)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PartyName,
		&i.Active,
	)
	return i, err
}

const GetPartyByPartyName = `-- name: GetPartyByPartyName :one
SELECT id, created_at, updated_at, party_name, active FROM parties
WHERE party_name = $1
`

func (q *Queries) GetPartyByPartyName(ctx context.Context, partyName string) (Party, error) {
	row := q.db.QueryRow(ctx, GetPartyByPartyName, partyName)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PartyName,
		&i.Active,
	)
	return i, err
}

const UpdateParty = `-- name: UpdateParty :one
UPDATE parties
SET ( updated_at, party_name, active ) = (NOW(), $2, $3)
WHERE id = $1
RETURNING id, created_at, updated_at, party_name, active
`

type UpdatePartyParams struct {
	ID        uuid.UUID `json:"id"`
	PartyName string    `json:"party_name"`
	Active    bool      `json:"active"`
}

func (q *Queries) UpdateParty(ctx context.Context, arg UpdatePartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, UpdateParty, arg.ID, arg.PartyName, arg.Active)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PartyName,
		&i.Active,
	)
	return i, err
}
