// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform_keys.sql

package database

import (
	"context"
	"encoding/json"
)

const DeletePlatformKey = `-- name: DeletePlatformKey :exec
DELETE FROM platform_keys
WHERE platform_id = $1
`

func (q *Queries) DeletePlatformKey(ctx context.Context, platformID string) error {
	_, err := q.db.Exec(ctx, DeletePlatformKey, platformID)
	return err
}

const GetPlatformKey = `-- name: GetPlatformKey :one
SELECT id, created_at, updated_at, platform_id, platform_name, jwks FROM platform_keys
WHERE platform_id = $1
`

func (q *Queries) GetPlatformKey(ctx context.Context, platformID string) (PlatformKey, error) {
	row := q.db.QueryRow(ctx, GetPlatformKey, platformID)
	var i PlatformKey
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlatformID,
		&i.PlatformName,
		&i.Jwks,
	)
	return i, err
}

const ListPlatformKeys = `-- name: ListPlatformKeys :many
SELECT id, created_at, updated_at, platform_id, platform_name, jwks FROM platform_keys
ORDER BY platform_id ASC
`

func (q *Queries) ListPlatformKeys(ctx context.Context) ([]PlatformKey, error) {
	rows, err := q.db.Query(ctx, ListPlatformKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformKey
	for rows.Next() {
		var i PlatformKey
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlatformID,
			&i.PlatformName,
			&i.Jwks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertPlatformKey = `-- name: UpsertPlatformKey :one
INSERT INTO platform_keys (
    id,
    created_at,
    updated_at,
    platform_id,
    platform_name,
    jwks
) VALUES (
    gen_random_uuid(),
    now(),
    now(),
    $1, $2, $3
)
ON CONFLICT (platform_id)
DO UPDATE SET
    (updated_at, platform_name, jwks) = (now(), EXCLUDED.platform_name, EXCLUDED.jwks)
RETURNING id, created_at, updated_at, platform_id, platform_name, jwks
`

type UpsertPlatformKeyParams struct {
	PlatformID   string          `json:"platform_id"`
	PlatformName *string         `json:"platform_name"`
	Jwks         json.RawMessage `json:"jwks"`
}

func (q *Queries) UpsertPlatformKey(ctx context.Context, arg UpsertPlatformKeyParams) (PlatformKey, error) {
	row := q.db.QueryRow(ctx, UpsertPlatformKey, arg.PlatformID, arg.PlatformName, arg.Jwks)
	var i PlatformKey
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlatformID,
		&i.PlatformName,
		&i.Jwks,
	)
	return i, err
}
