// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfer_chain_entries.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const CreateTransferChainEntry = `-- name: CreateTransferChainEntry :one
INSERT INTO transfer_chain_entries (
    id,
    created_at,
    transport_document_checksum,
    envelope_id,
    signed_content,
    entry_checksum,
    previous_entry_checksum,
    sequence
) VALUES (
    gen_random_uuid(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING id, created_at, transport_document_checksum, envelope_id, signed_content, entry_checksum, previous_entry_checksum, sequence
`

type CreateTransferChainEntryParams struct {
	TransportDocumentChecksum string    `json:"transport_document_checksum"`
	EnvelopeID                uuid.UUID `json:"envelope_id"`
	SignedContent             string    `json:"signed_content"`
	EntryChecksum             string    `json:"entry_checksum"`
	PreviousEntryChecksum     *string   `json:"previous_entry_checksum"`
	Sequence                  int32     `json:"sequence"`
}

// Create a new transfer chain entry
func (q *Queries) CreateTransferChainEntry(ctx context.Context, arg CreateTransferChainEntryParams) (TransferChainEntry, error) {
	row := q.db.QueryRow(ctx, CreateTransferChainEntry,
		arg.TransportDocumentChecksum,
		arg.EnvelopeID,
		arg.SignedContent,
		arg.EntryChecksum,
		arg.PreviousEntryChecksum,
		arg.Sequence,
	)
	var i TransferChainEntry
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.TransportDocumentChecksum,
		&i.EnvelopeID,
		&i.SignedContent,
		&i.EntryChecksum,
		&i.PreviousEntryChecksum,
		&i.Sequence,
	)
	return i, err
}

const GetTransferChainEntriesByTransportDocumentChecksum = `-- name: GetTransferChainEntriesByTransportDocumentChecksum :many
SELECT id, created_at, transport_document_checksum, envelope_id, signed_content, entry_checksum, previous_entry_checksum, sequence FROM transfer_chain_entries
WHERE transport_document_checksum = $1
ORDER BY created_at ASC
`

// Get all transfer chain entries for a given eBL
// Returns entries ordered by creation time
func (q *Queries) GetTransferChainEntriesByTransportDocumentChecksum(ctx context.Context, transportDocumentChecksum string) ([]TransferChainEntry, error) {
	rows, err := q.db.Query(ctx, GetTransferChainEntriesByTransportDocumentChecksum, transportDocumentChecksum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransferChainEntry
	for rows.Next() {
		var i TransferChainEntry
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.TransportDocumentChecksum,
			&i.EnvelopeID,
			&i.SignedContent,
			&i.EntryChecksum,
			&i.PreviousEntryChecksum,
			&i.Sequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTransferChainEntryByChecksum = `-- name: GetTransferChainEntryByChecksum :one
SELECT id, created_at, transport_document_checksum, envelope_id, signed_content, entry_checksum, previous_entry_checksum, sequence FROM transfer_chain_entries
WHERE entry_checksum = $1
`

// Get a specific transfer chain entry by its checksum
func (q *Queries) GetTransferChainEntryByChecksum(ctx context.Context, entryChecksum string) (TransferChainEntry, error) {
	row := q.db.QueryRow(ctx, GetTransferChainEntryByChecksum, entryChecksum)
	var i TransferChainEntry
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.TransportDocumentChecksum,
		&i.EnvelopeID,
		&i.SignedContent,
		&i.EntryChecksum,
		&i.PreviousEntryChecksum,
		&i.Sequence,
	)
	return i, err
}

const ListTransferChainEntries = `-- name: ListTransferChainEntries :many
SELECT id, created_at, transport_document_checksum, envelope_id, signed_content, entry_checksum, previous_entry_checksum, sequence FROM transfer_chain_entries
WHERE envelope_id = $1
ORDER BY sequence ASC
`

// Get all transfer chain entries for a given envelope
// Returns entries ordered by sequence
func (q *Queries) ListTransferChainEntries(ctx context.Context, envelopeID uuid.UUID) ([]TransferChainEntry, error) {
	rows, err := q.db.Query(ctx, ListTransferChainEntries, envelopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransferChainEntry
	for rows.Next() {
		var i TransferChainEntry
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.TransportDocumentChecksum,
			&i.EnvelopeID,
			&i.SignedContent,
			&i.EntryChecksum,
			&i.PreviousEntryChecksum,
			&i.Sequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
