// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transport_documents.sql

package database

import (
	"context"
	"encoding/json"
)

const CreateTransportDocumentIfNew = `-- name: CreateTransportDocumentIfNew :one
INSERT INTO transport_documents (
    checksum,
    created_at,
    content
) VALUES (
    $1,
    NOW(),
    $2
)
ON CONFLICT (checksum) DO NOTHING
RETURNING checksum, created_at, content
`

type CreateTransportDocumentIfNewParams struct {
	Checksum string          `json:"checksum"`
	Content  json.RawMessage `json:"content"`
}

// Insert transport document if it doesn't exist, otherwise return existing
// This is used when receiving a new envelope transfer
func (q *Queries) CreateTransportDocumentIfNew(ctx context.Context, arg CreateTransportDocumentIfNewParams) (TransportDocument, error) {
	row := q.db.QueryRow(ctx, CreateTransportDocumentIfNew, arg.Checksum, arg.Content)
	var i TransportDocument
	err := row.Scan(&i.Checksum, &i.CreatedAt, &i.Content)
	return i, err
}

const GetTransportDocument = `-- name: GetTransportDocument :one
SELECT checksum, created_at, content FROM transport_documents
WHERE checksum = $1
`

// Get transport document by checksum
func (q *Queries) GetTransportDocument(ctx context.Context, checksum string) (TransportDocument, error) {
	row := q.db.QueryRow(ctx, GetTransportDocument, checksum)
	var i TransportDocument
	err := row.Scan(&i.Checksum, &i.CreatedAt, &i.Content)
	return i, err
}

const GetTransportDocumentPossessor = `-- name: GetTransportDocumentPossessor :one
SELECT envelope_id, transport_document_checksum, action_code, possessor_platform_code, created_at, accepted_at FROM transport_document_possessor
WHERE transport_document_checksum = $1
`

// Get the platform that currently possesses the eBL.
//
// Note the platform may have accepted actions for eBLs they don't possess:
// for insance, a transfer is pending additional docs, or it has received an endorsement
// action, but have not yet received the transfer action.
//
// Use this query before determing what action to take when receiving a new envelope transfer.
func (q *Queries) GetTransportDocumentPossessor(ctx context.Context, transportDocumentChecksum string) (TransportDocumentPossessor, error) {
	row := q.db.QueryRow(ctx, GetTransportDocumentPossessor, transportDocumentChecksum)
	var i TransportDocumentPossessor
	err := row.Scan(
		&i.EnvelopeID,
		&i.TransportDocumentChecksum,
		&i.ActionCode,
		&i.PossessorPlatformCode,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const GetTransportDocumentState = `-- name: GetTransportDocumentState :one
SELECT envelope_id, transport_document_checksum, action_code, sent_by_platform_code, received_by_platform_code, created_at, accepted, accepted_at FROM transport_document_state
WHERE transport_document_checksum = $1
`

// Get the current state of the eBL on this platform
func (q *Queries) GetTransportDocumentState(ctx context.Context, transportDocumentChecksum string) (TransportDocumentState, error) {
	row := q.db.QueryRow(ctx, GetTransportDocumentState, transportDocumentChecksum)
	var i TransportDocumentState
	err := row.Scan(
		&i.EnvelopeID,
		&i.TransportDocumentChecksum,
		&i.ActionCode,
		&i.SentByPlatformCode,
		&i.ReceivedByPlatformCode,
		&i.CreatedAt,
		&i.Accepted,
		&i.AcceptedAt,
	)
	return i, err
}
