// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfer_chain.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const CountTransferChainEntries = `-- name: CountTransferChainEntries :one
SELECT COUNT(*) FROM transfer_chain_entries
WHERE envelope_id = $1
`

func (q *Queries) CountTransferChainEntries(ctx context.Context, envelopeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountTransferChainEntries, envelopeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateTransferChainEntry = `-- name: CreateTransferChainEntry :one
INSERT INTO transfer_chain_entries (
    id,
    created_at,
    envelope_id,
    signed_content,
    sequence
) VALUES (
    gen_random_uuid(),
    now(),
    $1, $2, $3
) RETURNING id, created_at, envelope_id, signed_content, sequence
`

type CreateTransferChainEntryParams struct {
	EnvelopeID    uuid.UUID `json:"envelope_id"`
	SignedContent string    `json:"signed_content"`
	Sequence      int32     `json:"sequence"`
}

func (q *Queries) CreateTransferChainEntry(ctx context.Context, arg CreateTransferChainEntryParams) (TransferChainEntry, error) {
	row := q.db.QueryRow(ctx, CreateTransferChainEntry, arg.EnvelopeID, arg.SignedContent, arg.Sequence)
	var i TransferChainEntry
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.EnvelopeID,
		&i.SignedContent,
		&i.Sequence,
	)
	return i, err
}

const GetLatestTransferChainEntry = `-- name: GetLatestTransferChainEntry :one
SELECT id, created_at, envelope_id, signed_content, sequence FROM transfer_chain_entries
WHERE envelope_id = $1
ORDER BY sequence DESC
LIMIT 1
`

func (q *Queries) GetLatestTransferChainEntry(ctx context.Context, envelopeID uuid.UUID) (TransferChainEntry, error) {
	row := q.db.QueryRow(ctx, GetLatestTransferChainEntry, envelopeID)
	var i TransferChainEntry
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.EnvelopeID,
		&i.SignedContent,
		&i.Sequence,
	)
	return i, err
}

const ListTransferChainEntries = `-- name: ListTransferChainEntries :many
SELECT id, created_at, envelope_id, signed_content, sequence FROM transfer_chain_entries
WHERE envelope_id = $1
ORDER BY sequence ASC
`

func (q *Queries) ListTransferChainEntries(ctx context.Context, envelopeID uuid.UUID) ([]TransferChainEntry, error) {
	rows, err := q.db.Query(ctx, ListTransferChainEntries, envelopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransferChainEntry
	for rows.Next() {
		var i TransferChainEntry
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.EnvelopeID,
			&i.SignedContent,
			&i.Sequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
