// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transport_documents.sql

package database

import (
	"context"
	"encoding/json"
)

const GetTransportDocument = `-- name: GetTransportDocument :one
SELECT checksum, content, first_seen_at, first_received_from_platform_code FROM transport_documents
WHERE checksum = $1
`

// Get transport document by checksum
func (q *Queries) GetTransportDocument(ctx context.Context, checksum string) (TransportDocument, error) {
	row := q.db.QueryRow(ctx, GetTransportDocument, checksum)
	var i TransportDocument
	err := row.Scan(
		&i.Checksum,
		&i.Content,
		&i.FirstSeenAt,
		&i.FirstReceivedFromPlatformCode,
	)
	return i, err
}

const UpsertTransportDocument = `-- name: UpsertTransportDocument :one
INSERT INTO transport_documents (
    checksum,
    content,
    first_seen_at,
    first_received_from_platform_code
) VALUES (
    $1,
    $2,
    NOW(),
    $3
)
ON CONFLICT (checksum) DO NOTHING
RETURNING checksum, content, first_seen_at, first_received_from_platform_code
`

type UpsertTransportDocumentParams struct {
	Checksum                      string          `json:"checksum"`
	Content                       json.RawMessage `json:"content"`
	FirstReceivedFromPlatformCode string          `json:"first_received_from_platform_code"`
}

// Insert transport document if it doesn't exist, otherwise return existing
// This is used when receiving a new envelope transfer
func (q *Queries) UpsertTransportDocument(ctx context.Context, arg UpsertTransportDocumentParams) (TransportDocument, error) {
	row := q.db.QueryRow(ctx, UpsertTransportDocument, arg.Checksum, arg.Content, arg.FirstReceivedFromPlatformCode)
	var i TransportDocument
	err := row.Scan(
		&i.Checksum,
		&i.Content,
		&i.FirstSeenAt,
		&i.FirstReceivedFromPlatformCode,
	)
	return i, err
}
