// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfer_chain_entries.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const CreateTransferChainEntry = `-- name: CreateTransferChainEntry :one
INSERT INTO transfer_chain_entries (
    signed_content_payload_checksum,
    transport_document_checksum,
    envelope_id,
    signed_content,
    signed_content_checksum,
    previous_signed_content_checksum,
    sequence
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
) RETURNING signed_content_payload_checksum, created_at, transport_document_checksum, envelope_id, signed_content, signed_content_checksum, previous_signed_content_checksum, sequence
`

type CreateTransferChainEntryParams struct {
	SignedContentPayloadChecksum  string    `json:"signed_content_payload_checksum"`
	TransportDocumentChecksum     string    `json:"transport_document_checksum"`
	EnvelopeID                    uuid.UUID `json:"envelope_id"`
	SignedContent                 string    `json:"signed_content"`
	SignedContentChecksum         string    `json:"signed_content_checksum"`
	PreviousSignedContentChecksum *string   `json:"previous_signed_content_checksum"`
	Sequence                      int32     `json:"sequence"`
}

// Create a new transfer chain entry
func (q *Queries) CreateTransferChainEntry(ctx context.Context, arg CreateTransferChainEntryParams) (TransferChainEntry, error) {
	row := q.db.QueryRow(ctx, CreateTransferChainEntry,
		arg.SignedContentPayloadChecksum,
		arg.TransportDocumentChecksum,
		arg.EnvelopeID,
		arg.SignedContent,
		arg.SignedContentChecksum,
		arg.PreviousSignedContentChecksum,
		arg.Sequence,
	)
	var i TransferChainEntry
	err := row.Scan(
		&i.SignedContentPayloadChecksum,
		&i.CreatedAt,
		&i.TransportDocumentChecksum,
		&i.EnvelopeID,
		&i.SignedContent,
		&i.SignedContentChecksum,
		&i.PreviousSignedContentChecksum,
		&i.Sequence,
	)
	return i, err
}

const GetTransferChainEntriesByTransportDocumentChecksum = `-- name: GetTransferChainEntriesByTransportDocumentChecksum :many
SELECT signed_content_payload_checksum, created_at, transport_document_checksum, envelope_id, signed_content, signed_content_checksum, previous_signed_content_checksum, sequence FROM transfer_chain_entries
WHERE transport_document_checksum = $1
ORDER BY sequence ASC
`

// Get all transfer chain entries for a given eBL
// Returns entries ordered by sequence
func (q *Queries) GetTransferChainEntriesByTransportDocumentChecksum(ctx context.Context, transportDocumentChecksum string) ([]TransferChainEntry, error) {
	rows, err := q.db.Query(ctx, GetTransferChainEntriesByTransportDocumentChecksum, transportDocumentChecksum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransferChainEntry
	for rows.Next() {
		var i TransferChainEntry
		if err := rows.Scan(
			&i.SignedContentPayloadChecksum,
			&i.CreatedAt,
			&i.TransportDocumentChecksum,
			&i.EnvelopeID,
			&i.SignedContent,
			&i.SignedContentChecksum,
			&i.PreviousSignedContentChecksum,
			&i.Sequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTransferChainEntryByJWSChecksum = `-- name: GetTransferChainEntryByJWSChecksum :one
SELECT signed_content_payload_checksum, created_at, transport_document_checksum, envelope_id, signed_content, signed_content_checksum, previous_signed_content_checksum, sequence FROM transfer_chain_entries
WHERE signed_content_checksum = $1
`

// Get a specific transfer chain entry by its JWS checksum
func (q *Queries) GetTransferChainEntryByJWSChecksum(ctx context.Context, signedContentChecksum string) (TransferChainEntry, error) {
	row := q.db.QueryRow(ctx, GetTransferChainEntryByJWSChecksum, signedContentChecksum)
	var i TransferChainEntry
	err := row.Scan(
		&i.SignedContentPayloadChecksum,
		&i.CreatedAt,
		&i.TransportDocumentChecksum,
		&i.EnvelopeID,
		&i.SignedContent,
		&i.SignedContentChecksum,
		&i.PreviousSignedContentChecksum,
		&i.Sequence,
	)
	return i, err
}

const GetTransferChainEntryByPayloadChecksum = `-- name: GetTransferChainEntryByPayloadChecksum :one
SELECT signed_content_payload_checksum, created_at, transport_document_checksum, envelope_id, signed_content, signed_content_checksum, previous_signed_content_checksum, sequence FROM transfer_chain_entries
WHERE signed_content_payload_checksum = $1
`

// Get a specific transfer chain entry by its payload checksum
func (q *Queries) GetTransferChainEntryByPayloadChecksum(ctx context.Context, signedContentPayloadChecksum string) (TransferChainEntry, error) {
	row := q.db.QueryRow(ctx, GetTransferChainEntryByPayloadChecksum, signedContentPayloadChecksum)
	var i TransferChainEntry
	err := row.Scan(
		&i.SignedContentPayloadChecksum,
		&i.CreatedAt,
		&i.TransportDocumentChecksum,
		&i.EnvelopeID,
		&i.SignedContent,
		&i.SignedContentChecksum,
		&i.PreviousSignedContentChecksum,
		&i.Sequence,
	)
	return i, err
}

const ListTransferChainEntries = `-- name: ListTransferChainEntries :many
SELECT signed_content_payload_checksum, created_at, transport_document_checksum, envelope_id, signed_content, signed_content_checksum, previous_signed_content_checksum, sequence FROM transfer_chain_entries
WHERE envelope_id = $1
ORDER BY sequence ASC
`

// Get all transfer chain entries for a given envelope
// Returns entries ordered by sequence
func (q *Queries) ListTransferChainEntries(ctx context.Context, envelopeID uuid.UUID) ([]TransferChainEntry, error) {
	rows, err := q.db.Query(ctx, ListTransferChainEntries, envelopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransferChainEntry
	for rows.Next() {
		var i TransferChainEntry
		if err := rows.Scan(
			&i.SignedContentPayloadChecksum,
			&i.CreatedAt,
			&i.TransportDocumentChecksum,
			&i.EnvelopeID,
			&i.SignedContent,
			&i.SignedContentChecksum,
			&i.PreviousSignedContentChecksum,
			&i.Sequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
