#!/bin/bash

# make the certs needed to test pint-demo
# the script uses the keygen CLI to generate the key pairs in JWK files and PEM files
# the PEMs are used to create CSRs which are then signed by the test CAs to create the certificates used in testing
# 
# four valid leaf certs are created:
# 1. ed25519 signed cert (ed25519-eblplatform.example.com)
# 2. rsa signed cert (rsa-eblplatform.example.com)
# 3. ecdsa signed cert (ed25519-carrier.example.com)
# 3. ecdsa signed cert (rsa-carrier.example.com)
#
# the invalid/expired certs are created by reusing the keys from the valid ed25519-eblplatform.example.com cert


set -e

function usage() {
  echo "Usage: $0 -d <project_root_dir>"
  exit 1
}

# create a self-signed cert for root CAs
function create_root_CA_cert() {
    local filename=$1
    local O=$2
    local CN=$2

    # generates its own key (for CAs that don't need JWK)
    openssl req -x509 -newkey ed25519 -nodes \
        -keyout "$CERTS_DIR/${filename}.pem" \
        -out "$CERTS_DIR/${filename}.crt" \
        -days $EXPIRY_DAYS \
        -subj "/C=GB/ST=England/L=London/O=${O}/CN=${CN}"
    if [ $? -ne 0 ]; then
        echo "Error: openssl req failed" >&2
        return 1
    fi
}

function create_intermediate_CA_signing_request() {
    local filename=$1
    local O=$2
    local CN=$2

    # generates its own key (for CAs that don't need JWK)
    openssl req -newkey ed25519 -nodes \
        -keyout "$CERTS_DIR/${filename}.pem" \
        -out "$CERTS_DIR/${filename}.csr" \
        -subj "/C=GB/ST=England/L=London/O=${O}/CN=${CN}"
    if [ $? -ne 0 ]; then
        echo "Error: openssl req failed" >&2
        return 1
    fi
}

function sign_intermediate_CA_certificate() {

    local ca=$1
    local cert=$2
    openssl x509 -req -in "$CERTS_DIR/${cert}.csr" \
        -CA "$CERTS_DIR/${ca}.crt" \
        -CAkey "$CERTS_DIR/${ca}.pem" \
        -CAcreateserial \
        -out "$CERTS_DIR/${cert}.crt" \
        -days $EXPIRY_DAYS \
        -extfile <(echo "basicConstraints=CA:TRUE")  # mark as CA so it can sign other certs
    if [ $? -ne 0 ]; then
        echo "Error: openssl x509 failed" >&2
        return 1
    fi
}


# use this to create keys for a test eblplatform 
function generate_platform_keypair() {
    local hostname=$1   
    go run cmd/keygen/main.go --type ed25519 --hostname $hostname --outputdir $KEYS_DIR
    if [ $? -ne 0 ]; then
        echo "Error: keygen failed" >&2
        return 1
    fi
}   

function generate_rsa_platform_keypair() {
    local hostname=$1   
    go run cmd/keygen/main.go --type rsa -s 2048 --hostname $hostname --outputdir $KEYS_DIR
    if [ $? -ne 0 ]; then
        echo "Error: keygen failed" >&2
        return 1
    fi
}   

function create_platform_signing_request() {
    local hostname=$1
    local O=$2

    # Use the PEM key generated by keygen
    local pem_key="$KEYS_DIR/${hostname}.private.pem"

    if [ ! -f "$pem_key" ]; then
        echo "Error: PEM key not found: $pem_key" >&2
        exit 1
    fi

    # Create CSR using the existing key
    openssl req -new -key $pem_key \
        -out "$CERTS_DIR/${hostname}.csr" \
        -subj "/C=GB/ST=England/L=London/O=${O}/CN=${hostname}"
    if [ $? -ne 0 ]; then
        echo "Error: openssl req failed" >&2
        exit 1
    fi
}

function sign_platform_certificate() {
    local ca=$1
    local cert=$2
    openssl x509 -req -in "$CERTS_DIR/${cert}.csr" \
        -CA "$CERTS_DIR/${ca}.crt" \
        -CAkey "$CERTS_DIR/${ca}.pem" \
        -CAcreateserial \
        -out "$CERTS_DIR/${cert}.crt" \
        -days $EXPIRY_DAYS
    if [ $? -ne 0 ]; then
        echo "Error: openssl x509 failed" >&2
        exit 1
    fi
}   

# note the expiry days - wait 1 day before using in test
function sign_expired_eblplatform_certificate() {
    local ca=$1 
    local hostname=$2               
    openssl x509 -req -in "$CERTS_DIR/${hostname}.csr" \
        -CA "$CERTS_DIR/${ca}.crt" \
        -CAkey "$CERTS_DIR/${ca}.pem" \
        -CAcreateserial \
        -out "$CERTS_DIR/${hostname}.crt" \
        -days 1
    if [ $? -ne 0 ]; then
        echo "Error: openssl x509 failed" >&2
        exit 1
    fi
}

#
# main
#

while getopts "d:h" o; do
  case ${o} in
    h) usage ;;
    d) PROJECT_ROOT_DIR="$OPTARG" ;;
    ?) usage ;;
  esac
done

#
# set up env
#

PATH="/opt/homebrew/opt/openssl@3/bin:$PATH" # v3.6 needed for ed25519 support
EXPIRY_DAYS=3650

PROJECT_ROOT_DIR=$(realpath $PROJECT_ROOT_DIR)

if [ -z "$PROJECT_ROOT_DIR" ]; then
  echo "test data dir not specified" >&2
  usage
fi

if [ ! -d "$PROJECT_ROOT_DIR" ]; then
    echo "could not open test data dir: $PROJECT_ROOT_DIR" >&2
    exit 1
fi  


if  [ ! -f $PROJECT_ROOT_DIR/app/go.mod ]; then
    echo "could not find $PROJECT_ROOT_DIR/app/go.mod" >&2
    exit 1
fi  
TEST_DATA_DIR="$PROJECT_ROOT_DIR/app/internal/crypto/testdata"

mkdir -p "$TEST_DATA_DIR"
if [ $? -ne 0 ]; then
    echo "could not create test data dir: $TEST_DATA_DIR" >&2
    exit 1
fi  

CERTS_DIR="$TEST_DATA_DIR/certs"

KEYS_DIR="$TEST_DATA_DIR/keys" # keygen output (JWK and PEM)
KEYGEN_DIR="$PROJECT_ROOT_DIR/app/cmd/keygen"

mkdir -p "$CERTS_DIR"
if [ $? -ne 0 ]; then
    echo "could not create certs dir: $CERTS_DIR" >&2
    exit 1
fi  

mkdir -p "$KEYS_DIR"
if [ $? -ne 0 ]; then
    echo "could not create keys dir: $KEYS_DIR" >&2
    exit 1
fi  

# execute keygen from the app dir
cd $PROJECT_ROOT_DIR/app
if [ $? -ne 0 ]; then
    echo "could not change to project dir: $PROJECT_ROOT_DIR/app" >&2
    exit 1
fi  

# 
# generate the test certs
#
echo "1. Generating valid certificate chain ..."

echo -e "\n  Creating Root CA..."
create_root_CA_cert "root-ca" "Test Root CA"

echo -e "\n   Creating Intermediate CA signing request..."
create_intermediate_CA_signing_request "intermediate-ca" "Test Intermediate CA"


echo -e "\n   Signing Intermediate CA..."
sign_intermediate_CA_certificate root-ca intermediate-ca 

# valid ed25519 eblplatform keys
echo -e "\n   Generating key pair for valid server leaf certificate (eblplatform.example.com)..."
generate_platform_keypair "ed25519-eblplatform.example.com"

echo -e "\n   Creating CSR from keygen key..."
create_platform_signing_request "ed25519-eblplatform.example.com" "eblplatform" 

echo -e "\n   Signing valid server leaf certificate..."
sign_platform_certificate intermediate-ca ed25519-eblplatform.example.com

echo -e "\n   Creating full chain file... (ed25519-eblplatform-fullchain.crt)"
cat "$CERTS_DIR/ed25519-eblplatform.example.com.crt" "$CERTS_DIR/intermediate-ca.crt" "$CERTS_DIR/root-ca.crt" > "$CERTS_DIR/ed25519-eblplatform.example.com-fullchain.crt"

# expired ed25519 eblplatform keys
echo -e "\n2. Generating expired certificate (ed25519-eblplatform-expired.example.com)..."

echo -e "\n   Generating key pair for expired certificate..."
generate_platform_keypair "ed25519-eblplatform-expired.example.com"

echo -e "\n   Creating CSR from keygen key..."
create_platform_signing_request "ed25519-eblplatform-expired.example.com" "ed25519-eblplatform-expired" 

echo -e "\n   Signing expired server leaf certificate..."
sign_expired_eblplatform_certificate intermediate-ca ed25519-eblplatform-expired.example.com

echo -e "\n   Creating expired full chain file (ed25519-eblplatform-expired-fullchain.crt)..."
cat "$CERTS_DIR/ed25519-eblplatform-expired.example.com.crt" "$CERTS_DIR/intermediate-ca.crt" "$CERTS_DIR/root-ca.crt" > "$CERTS_DIR/ed25519-eblplatform-expired.example.com-fullchain.crt"

# invalid cert chain
echo -e "\n3. Generating invalid certificate chain ..."

echo -e "\n   Creating untrusted CA..."
create_root_CA_cert "untrusted-ca" "Untrusted CA"

echo -e "\n   Generating key pair for invalid certificate (ed25519-eblplatform-invalid.example.com)..."
generate_platform_keypair "ed25519-eblplatform-invalid.example.com"

echo -e "\n   Creating CSR from keygen key..."
create_platform_signing_request "ed25519-eblplatform-invalid.example.com" "ed25519-eblplatform-invalid" 

echo -e "\n   Signing server leaf cert with untrusted CA..."
sign_platform_certificate untrusted-ca ed25519-eblplatform-invalid.example.com

echo -e "\n   Creating invalid chain file (ed25519-eblplatform-invalid-fullchain.crt)..."
cat "$CERTS_DIR/ed25519-eblplatform-invalid.example.com.crt" "$CERTS_DIR/intermediate-ca.crt" "$CERTS_DIR/root-ca.crt" > "$CERTS_DIR/ed25519-eblplatform-invalid.example.com-fullchain.crt"

# valid rsa eblplatform keys
echo -e "\n4. Generating valid RSA certificate (rsa-eblplatform.example.com)..."

echo -e "\n   Generating RSA key pair for valid server leaf certificate (rsa-eblplatform.example.com)..."
generate_rsa_platform_keypair "rsa-eblplatform.example.com"

echo -e "\n   Creating CSR from keygen key..."
create_platform_signing_request "rsa-eblplatform.example.com" "rsa-eblplatform" 

echo -e "\n   Signing valid RSA server leaf certificate..."
sign_platform_certificate intermediate-ca rsa-eblplatform.example.com

echo -e "\n   Creating RSA full chain file... (rsa-eblplatform-fullchain.crt)"
cat "$CERTS_DIR/rsa-eblplatform.example.com.crt" "$CERTS_DIR/intermediate-ca.crt" "$CERTS_DIR/root-ca.crt" > "$CERTS_DIR/rsa-eblplatform.example.com-fullchain.crt"

# carrier cert (ed25519)
echo -e "\n5. Generating valid carrier certificate (ed25519-carrier.example.com)..."

echo -e "\n   Generating ECDSA key pair for valid server leaf certificate (ed25519-carrier.example.com)..." 
generate_platform_keypair "ed25519-carrier.example.com"

echo -e "\n   Creating CSR from keygen key..."
create_platform_signing_request "ed25519-carrier.example.com" "ed25519-carrier" 

echo -e "\n   Signing valid ed25519-carrier leaf certificate..."    
sign_platform_certificate intermediate-ca ed25519-carrier.example.com    

echo -e "\n   Creating ed25519-carrier full chain file... (ed25519-carrier-fullchain.crt)"
cat "$CERTS_DIR/ed25519-carrier.example.com.crt" "$CERTS_DIR/intermediate-ca.crt" "$CERTS_DIR/root-ca.crt" > "$CERTS_DIR/ed25519-carrier.example.com-fullchain.crt"

# carrier cert (rsa)    
echo -e "\n6. Generating valid carrier certificate (rsa-carrier.example.com)..."

echo -e "\n   Generating ECDSA key pair for valid server leaf certificate (ed25519-carrier.example.com)..." 
generate_rsa_platform_keypair "rsa-carrier.example.com"

echo -e "\n   Creating CSR from keygen key..."
create_platform_signing_request "rsa-carrier.example.com" "rsa-carrier" 

echo -e "\n   Signing valid rsa-carrier leaf certificate..."    
sign_platform_certificate intermediate-ca rsa-carrier.example.com    

echo -e "\n   Creating rsa-carrier full chain file... (rsa-carrier-fullchain.crt)"
cat "$CERTS_DIR/rsa-carrier.example.com.crt" "$CERTS_DIR/intermediate-ca.crt" "$CERTS_DIR/root-ca.crt" > "$CERTS_DIR/rsa-carrier.example.com-fullchain.crt"


# clean up
echo -e "\n   Cleaning up temporary files..."
rm -f "$CERTS_DIR"/*.csr "$CERTS_DIR"/*.srl



echo
echo "===================================================="
echo "Done!"
echo " Key pairs generated in: $KEYS_DIR"
echo " Certificates generated in: $CERTS_DIR"
